//*****************************************************************************
//
// This file is generated by png2bitmap; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include "tbitmap.h"

//*****************************************************************************
// Bitmap:       bmp_two
// Width:        5
// Height:       8
// Memory usage: 9 bytes
//*****************************************************************************

//*****************************************************************************
//
// The data for the bitmapbmp_two
//
//*****************************************************************************
static const unsigned char bmp_two_data[5 * 1] PROGMEM ={
	0x44, 0x62, 0x52, 0x52, 0x4c, 
};

//*****************************************************************************
//
// The bitmap definition
//
//*****************************************************************************
const struct tbitmap g_bmp_two PROGMEM =
{
	//
	// The format of the bitmap
	//
	BITMAP_UNCOMPRESSED,

	//
	// The width of the bitmap.
	//
	5,

	//
	// The height of the bitmap.
	//
	8,

	//
	// A stuffing byte for 4-byte alignment
	//
	0,

	//
	// A pointer to the table containing the bitmap data.
	//
	bmp_two_data
};

