//*****************************************************************************
//
// This file is generated by png2bitmap; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include "tbitmap.h"

//*****************************************************************************
// Bitmap:       bmp_thyristor
// Width:        19
// Height:       32
// Memory usage: 80 bytes
//*****************************************************************************

//*****************************************************************************
//
// The data for the bitmapbmp_thyristor
//
//*****************************************************************************
static const unsigned char bmp_thyristor_data[19 * 4] PROGMEM ={
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3c, 0x0a, 
	0x09, 0x0a, 0x3c, 0x00, 0xff, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x04, 0x0c, 0x1c, 0x3c, 0x7c, 0xff, 
	0x7c, 0x3c, 0x1c, 0x0c, 0x04, 0x00, 0x9e, 0xa1, 
	0xa9, 0xa9, 0x9a, 0x80, 0x43, 0x23, 0x13, 0x0b, 
	0x07, 0x03, 0xff, 0x03, 0x03, 0x03, 0x03, 0x03, 
	0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x78, 
	0x84, 0x84, 0x84, 0x48, 0x00, 0xff, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 
};

//*****************************************************************************
//
// The bitmap definition
//
//*****************************************************************************
const struct tbitmap g_bmp_thyristor PROGMEM =
{
	//
	// The format of the bitmap
	//
	BITMAP_UNCOMPRESSED,

	//
	// The width of the bitmap.
	//
	19,

	//
	// The height of the bitmap.
	//
	32,

	//
	// A stuffing byte for 4-byte alignment
	//
	0,

	//
	// A pointer to the table containing the bitmap data.
	//
	bmp_thyristor_data
};

