//*****************************************************************************
//
// This file is generated by png2bitmap; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include "tbitmap.h"

//*****************************************************************************
// Bitmap:       bmp_three
// Width:        5
// Height:       8
// Memory usage: 7 bytes
//*****************************************************************************

//*****************************************************************************
//
// The data for the bitmapbmp_three
//
//*****************************************************************************
static const unsigned char bmp_three_data[5 * 1] PROGMEM ={
	0x24, 0x42, 0x4a, 0x4a, 0x34, 
};

//*****************************************************************************
//
// The bitmap definition
//
//*****************************************************************************
const struct tbitmap g_bmp_three PROGMEM =
{
	//
	// The width of the bitmap.
	//
	5,

	//
	// The height of the bitmap.
	//
	8,

	//
	// A pointer to the table containing the bitmap data.
	//
	bmp_three_data
};

