//*****************************************************************************
//
// This file is generated by png2bitmap; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include "tbitmap.h"

//*****************************************************************************
// Bitmap:       bmp_inductor
// Width:        16
// Height:       8
// Memory usage: 18 bytes
//*****************************************************************************

//*****************************************************************************
//
// The data for the bitmapbmp_inductor
//
//*****************************************************************************
static const unsigned char bmp_inductor_data[16 * 1] PROGMEM ={
	0x40, 0x7e, 0x01, 0x01, 0x3e, 0x01, 0x01, 0x3e, 
	0x01, 0x01, 0x3e, 0x01, 0x01, 0x7e, 0x40, 0x40, 
};

//*****************************************************************************
//
// The bitmap definition
//
//*****************************************************************************
const struct tbitmap g_bmp_inductor PROGMEM =
{
	//
	// The width of the bitmap.
	//
	16,

	//
	// The height of the bitmap.
	//
	8,

	//
	// A pointer to the table containing the bitmap data.
	//
	bmp_inductor_data
};

