//*****************************************************************************
//
// This file is generated by png2bitmap; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include "tbitmap.h"

//*****************************************************************************
// Bitmap:       bmp_vakdiode
// Width:        8
// Height:       32
// Memory usage: 36 bytes
//*****************************************************************************

//*****************************************************************************
//
// The data for the bitmapbmp_vakdiode
//
//*****************************************************************************
static const unsigned char bmp_vakdiode_data[8 * 4] PROGMEM ={
	0x02, 0x02, 0x02, 0x02, 0xfe, 0x00, 0x00, 0x00, 
	0x00, 0x20, 0x60, 0xa0, 0x3f, 0xa0, 0x60, 0x20, 
	0x00, 0x02, 0x02, 0x02, 0xff, 0x02, 0x02, 0x02, 
	0x40, 0x40, 0x40, 0x40, 0x7f, 0x00, 0x00, 0x00, 
};

//*****************************************************************************
//
// The bitmap definition
//
//*****************************************************************************
const struct tbitmap g_bmp_vakdiode PROGMEM =
{
	//
	// The format of the bitmap
	//
	BITMAP_UNCOMPRESSED,

	//
	// The width of the bitmap.
	//
	8,

	//
	// The height of the bitmap.
	//
	32,

	//
	// A stuffing byte for 4-byte alignment
	//
	0,

	//
	// A pointer to the table containing the bitmap data.
	//
	bmp_vakdiode_data
};

