//*****************************************************************************
//
// This file is generated by png2bitmap; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include "tbitmap.h"

//*****************************************************************************
// Bitmap:       bmp_one
// Width:        5
// Height:       8
// Memory usage: 9 bytes
//*****************************************************************************

//*****************************************************************************
//
// The data for the bitmapbmp_one
//
//*****************************************************************************
static const unsigned char bmp_one_data[5 * 1] PROGMEM ={
	0x00, 0x08, 0x04, 0x7e, 0x00, 
};

//*****************************************************************************
//
// The bitmap definition
//
//*****************************************************************************
const struct tbitmap g_bmp_one PROGMEM =
{
	//
	// The format of the bitmap
	//
	BITMAP_UNCOMPRESSED,

	//
	// The width of the bitmap.
	//
	5,

	//
	// The height of the bitmap.
	//
	8,

	//
	// A stuffing byte for 4-byte alignment
	//
	0,

	//
	// A pointer to the table containing the bitmap data.
	//
	bmp_one_data
};

