
## General Flags
CC = gcc

CPP = g++

CFLAGS = -Wall



## Build
all:  font2ascii ascii2font


##Link
font2ascii: font2ascii.c
	$(CC)  $(CFLAGS) -o font2ascii font2ascii.c
ascii2font: ascii2font.c
	$(CC)  $(CFLAGS) -o ascii2font ascii2font.c
