
## General Flags
CC = gcc

CPP = g++

CFLAGS = -Wall -g



## Build
all:  font2ascii ascii2font ascii2font2


##Link
font2ascii: font2ascii.c
	$(CC)  $(CFLAGS) -o font2ascii font2ascii.c
ascii2font: ascii2font.c
	$(CC)  $(CFLAGS) -o ascii2font ascii2font.c
ascii2font2: ascii2font2.c
	$(CC)  $(CFLAGS) -o ascii2font2 ascii2font2.c
