#!/bin/bash
make clean
#
#AllEEprom="SUPPORT_EEPROM"
AllEEprom="SUPPORT_EEPROM"
#WITH_SOFT_UART="SOFT_UART"
# If you change the option name from SOFT_UART to somewhat else, the option is switched off!!
WITH_SOFT_UART="SFT_UART"
#  buildable platforms of somewhat questionable support level
echo " "; echo "***** make lilypad ******"
make lilypad $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make pro8 ******"
make pro8 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make pro16 ******"
make pro16 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make pro20 ******"
make pro20 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega328_pro8 ******"
make atmega328_pro8 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make sanguino ******"
make sanguino $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make mega1280 ******"
make mega1280 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make luminet ******"
make luminet $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make diecimila ******"
make diecimila $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make bobuino ******"
make bobuino $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make wildfirev2 ******"
make wildfirev2 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega32 ******"
make atmega32 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega88 ******"
make atmega88 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega168p ******"
make atmega168p $AllEEprom=1 $WITH_SOFT_UART=1

#
# Atmel development board targets
echo " "; echo "***** make xplained168pb ******"
make xplained168pb $AllEEprom=1
echo " "; echo "***** make xplained328p ******"
make xplained328p $AllEEprom=1
echo " "; echo "***** make xplained328pb ******"
make xplained328pb $AllEEprom=1

#
# The "big three" standard bootloaders.
# These need to be built AFTER the platforms, or they'll get renamed
echo " "; echo "***** make atmega8 ******"
make atmega8 $AllEEprom=1
echo " "; echo "***** make atmega88 ******"
make atmega168 $AllEEprom=1
# echo " "; echo "***** make atmega328 ******"
# make atmega328 $AllEEprom=1
echo " "; echo "***** make atmega328p ******"
make atmega328p $AllEEprom=1
#
make atmega88 $AllEEprom=1
echo " "; echo "***** make atmega168 ******"
echo " "; echo "***** make atmega164p ******"
make atmega164p $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega324p ******"
make atmega324p $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega644p ******"
make atmega644p $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega1284p ******"
make atmega1284p $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega165p ******"
make atmega165p $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega325p ******"
make atmega325p $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega645p ******"
make atmega645p $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega169 ******"
make atmega169 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega329 ******"
make atmega329 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega649 ******"
make atmega649 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega640 ******"
make atmega640 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make atmega1280 ******"
make atmega1280 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make attiny84 ******"
make attiny84 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make attiny85 ******"
make attiny85 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make attiny861 ******"
make attiny861 $AllEEprom=1 $WITH_SOFT_UART=1
echo " "; echo "***** make attiny1634 ******"
make attiny1634 $AllEEprom=1 $WITH_SOFT_UART=1

