#
# Makefile for "custom" platforms.   Add your board here.
#
# * Copyright 2013-2015 by Bill Westfield.  Part of Optiboot.
# * This software is licensed under version 2 of the Gnu Public Licence.
# * See optiboot.c for details.


wildfire: TARGET := $@
wildfire: AVR_FREQ := 16000000
wildfire: LED := B5
wildfire:
	$(MAKE) atmega1284p 

wildfire_isp:
	$(MAKE) wildfire ISP=1

