#!/bin/bash
make clean
#
# The "big three" standard bootloaders.
# These need to be built AFTER the platforms, or they'll get renamed
echo " "; echo "***** make atmega8_autoBaud_noLED ******"
make atmega8  LED_START_FLASHES=0 BAUD_RATE=42
mv optiboot_atmega8.lst optiboot_m8_autoBaud_noLED.lst
mv optiboot_atmega8.hex optiboot_m8_autoBaud_noLED.hex
echo " "; echo "***** make atmega8 ******"
make atmega8 

echo " "; echo "***** make atmega168_autoBaud_noLED ******"
make atmega168 LED_START_FLASHES=0 BAUD_RATE=52
mv optiboot_atmega168.lst optiboot_m168_autoBaud_noLED.lst
mv optiboot_atmega168.hex optiboot_m168_autoBaud_noLED.hex
echo " "; echo "***** make atmega168 ******"
make atmega168 

echo " "; echo "***** make atmega328 ******"
make atmega328

echo " "; echo "***** make atmega328p_autoBaud_noLED ******"
make atmega328p LED_START_FLASHES=0 BAUD_RATE=52
mv optiboot_atmega328p.lst optiboot_m328p_autoBaud_noLED.lst
mv optiboot_atmega328p.hex optiboot_m328p_autoBaud_noLED.hex
echo " "; echo "***** make atmega328p ******"
make atmega328p 
#


